### ISSUE TITLE
modal direction bug

### ISSUE THREAD

**Issue by daviprm** [MonkeyDevelopers/template-#6]
verificar qual o bug do modal, pois nao esta recebendo o direction...

basicamente o direction eh quem da o position pra ele, e nao ta funcionando o position

**Comment by caio-emidio** [comment]
Essa issue ta relacionada a https://github.com/MonkeyDevelopers/koro-ui/issues/1

**Comment by caio-emidio** [comment]
Resolvido atualizando koro-ui lib pra versao 0.0.29
