### ISSUE TITLE
Table Multiple Errors

### ISSUE THREAD

**Issue by caio-emidio** [MonkeyDevelopers/template-#7]
- [ ] Ao meu ver se nao tiver nenhum tipo de mudanca no headers, nao deveria ter nenhum tipo de tratamento pra linha.
- [ ] Paginacao deveria ser um case separado. Nao incluido de maneira automatica e com paginas que nada muda.
- [ ] Selection deveria ser um v-if. setada como default false. Caso eu queira essa funcionalidade. Deveria ter algo como 
```vue
<Table select/>
```

**Comment by daviprm** [comment]
solved my brother! 👍☝️
