### ISSUE TITLE
Fazer o de avatar

### ISSUE THREAD

**Issue by caio-emidio** [MonkeyDevelopers/template-#9]
Parece boco...
mas seria interessante ter um UIAvatar funcionando da seguinte maneira

```vue
<UIAvatar :src="monkey.jpg" name="Macaco Feliz" />
```

Caso ele tenha imagem ele ficaria assim:
![image](https://github.com/user-attachments/assets/64e1b0b4-e091-4bc8-93ec-e8cd62945334)

Caso nao tenha imagem ficaria assim:
![image](https://github.com/user-attachments/assets/07919891-99f1-4bb7-901b-86a6dd4ef417)

```vue
<UIAvatar :src="macaco.jpg" name="Macaco Feliz" circle />
```

Caso ele tenha imagem ele ficaria assim:
![image](https://github.com/user-attachments/assets/d85bcd44-24e8-4d6b-a1a2-7d91fb6989a9)

Caso nao tenha imagem
![image](https://github.com/user-attachments/assets/85b3a243-d261-4a0e-9f1a-a3ffed004b4b)

**Comment by daviprm** [comment]
sim foi
